export enum ErrorCode {
  OK = 'OK',
  BAD_REQUEST = 'BAD_REQUEST',
  UNIQUE = 'UNIQUE',
  NOT_FOUND = 'NOT_FOUND',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  AT_LEAST_ONE_PICKUP = 'AT_LEAST_ONE_PICKUP',
  TIMEOUT = 'TIMEOUT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
